package kelentong;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormItem extends javax.swing.JFrame {
    int harga_barang = 0; 
    int stokBarang = 0; 
    int id_barang = 0; 
    double total_harga = 0; 
    private String username; 
    private int saldo;
    
    public void setUsername(String username){ 
        this.username = username; 
    } 
    public void setSaldo(int saldo){ 
        this.saldo = saldo; 
    }
    
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No."); 
        model.addColumn("Nama Barang"); 
        model.addColumn("Stok Barang"); 
        model.addColumn("Harga Barang"); 
        try {
            String sql = "SELECT * FROM stok_barang"; 
            java.sql.Connection conn = (Connection)ConfigDB.config(); 
            java.sql.Statement stm = conn.createStatement(); 
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow( 
                        new Object[]{res.getString(1), res.getString(2), 
                            res.getString(3), res.getString(4)});
            }
            
            tblBarang.setModel(model);
            
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }
    
    private void kosongkan_data() {
        fieldJumlahBarang.setText("0"); 
        fieldKodePromo.setText("");
        
        txtHarga.setText("Rp. 0"); 
        txtPotongan.setText("Rp. 0"); 
        txtTotal.setText("Rp. 0"); 
        txtBarang.setText("(Barang)"); 
        txtStokBarang.setText("(stok barang)"); 
        harga_barang = 0;
    }
    
    /**
     * Creates new form FormItem
     */
    public FormItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        txtUser = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBarang = new javax.swing.JLabel();
        txtStokBarang = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldJumlahBarang = new javax.swing.JTextField();
        fieldKodePromo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtPotongan = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnBeli = new javax.swing.JButton();
        btnHitungHarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Saldo anda: ");

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        txtUser.setText("(user)");

        txtSaldo.setText("Rp.0");

        jLabel3.setText("Barang          :");

        jLabel4.setText("Stok Barang  :");

        txtBarang.setText("(barang)");

        txtStokBarang.setText("(stok barang)");

        jLabel5.setText("Jumlah Barang :");

        jLabel6.setText("Kode Promo    :");

        fieldJumlahBarang.setText("0");

        jLabel7.setText("Harga                 :");

        jLabel8.setText("Potongan Harga :");

        jLabel9.setText("Total Harga         :");

        txtHarga.setText("Rp.0");

        txtPotongan.setText("Rp.0");

        txtTotal.setText("Rp.0");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnBeli.setText("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        btnHitungHarga.setText("Hitung Harga");
        btnHitungHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBarang))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBatal)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStokBarang)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldKodePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnHitungHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPotongan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHarga))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTotal))
                                    .addComponent(btnBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSaldo))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHarga)
                    .addComponent(jLabel5)
                    .addComponent(fieldJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStokBarang)
                    .addComponent(jLabel6)
                    .addComponent(fieldKodePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPotongan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBeli)
                    .addComponent(btnBatal)
                    .addComponent(btnHitungHarga))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int baris = tblBarang.rowAtPoint(evt.getPoint());
        
        String id = tblBarang.getValueAt(baris, 0).toString(); 
        id_barang = Integer.parseInt(id); 
        
        String nim = tblBarang.getValueAt(baris, 1).toString(); 
        txtBarang.setText(nim); 
        
        String stkBarang = tblBarang.getValueAt(baris, 2).toString(); 
        stokBarang = Integer.parseInt(stkBarang); 
        txtStokBarang.setText(stkBarang); 
        
        String hargaString = tblBarang.getValueAt(baris, 3).toString(); 
        harga_barang = Integer.parseInt(hargaString); 
        
        fieldJumlahBarang.setText("1");
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        kosongkan_data();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHitungHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungHargaActionPerformed
        // TODO add your handling code here:
        boolean promo = false;

        int jumlah_dibeli = Integer.parseInt(fieldJumlahBarang.getText());

        if(jumlah_dibeli >= 0 && stokBarang != 0) {
            if(fieldKodePromo.getText().equals("TAHUNBARU2025")){
                promo = true;
            }
        }

        total_harga = harga_barang * jumlah_dibeli;

        txtHarga.setText("Rp. " + total_harga);

        if(promo){
            txtPotongan.setText("Rp. " + total_harga * 0.20);
            total_harga = total_harga - total_harga * 0.20;
        }

        txtTotal.setText("Rp. " + total_harga);
    }//GEN-LAST:event_btnHitungHargaActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // TODO add your handling code here:
        try{
            int jumlah_dibeli = Integer.parseInt(fieldJumlahBarang.getText());
            int total = (int) total_harga;
            if(stokBarang >= jumlah_dibeli){
                if(saldo >= total){
                    String sql = "UPDATE pelanggan SET saldo_pelanggan = "
                        + (saldo - total)
                        + " WHERE username = '" + username + "'";

                    saldo = saldo - total;

                    java.sql.Connection coon = (Connection)ConfigDB.config();
                    java.sql.PreparedStatement pstm = coon.prepareStatement(sql);
                    pstm.execute();

                    String sql2 = "UPDATE stok_barang SET jumlah_barang = "
                        + (stokBarang - jumlah_dibeli)
                        + " WHERE id_barang = " + id_barang;

                    java.sql.Connection coon2 = (Connection)ConfigDB.config();
                    java.sql.PreparedStatement pstm2 = coon2.prepareStatement(sql2);
                    pstm2.execute();

                    txtSaldo.setText(Integer.toString(saldo));
                    tampilkan_data();
                    kosongkan_data();
                    JOptionPane.showMessageDialog(null, "Terima kasih telah membeli!");
                }else{
                    JOptionPane.showMessageDialog(null, "Saldo kamu tidak cukup!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Stok barang tidak cukup!");
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBeliActionPerformed

    /**
     * @param username
     * @param saldo
     */
    
    
    public FormItem(String username, int saldo) {
    this.username = username;
    this.saldo = saldo;
    initComponents();
    tampilkan_data();
    txtUser.setText("Selamat datang di kelontong, " + username);
    txtSaldo.setText("Rp. " + Integer.toString(saldo));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnHitungHarga;
    private javax.swing.JTextField fieldJumlahBarang;
    private javax.swing.JTextField fieldKodePromo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBarang;
    private javax.swing.JLabel txtBarang;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtPotongan;
    private javax.swing.JLabel txtSaldo;
    private javax.swing.JLabel txtStokBarang;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
